### ISSUE TITLE
member controller location

### ISSUE THREAD

**Issue by ChangSol** [Sioria-YU/sioscms#1]
@Sioria-YU 

![image](https://user-images.githubusercontent.com/53078114/220521389-66b43f20-69ba-49c8-b907-0b4543152553.png)

member => account 쪽으로 속하는게 어떨지 😂

**Comment by Sioria-YU** [comment]
domain 쪽은 rest로 쓰고 member쪽은 jsp 연동 관련으로 쓰려고 계획 중
